name: create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      # - name: Restore Dependencies
      #   run: dotnet restore
      # - name: Build
      #   run: dotnet build --no-restore
      - name: test echo tag
        run: VTAG=$(echo ${GITHUB_REF:10})
      - name: fix leading v
        run: VERSION=${VTAG:1:-1} && echo $VERSION
      