name: create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: get version tag
        run: echo "VTAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - name: Restore Dependencies
        run: dotnet restore
      - name: build
        run: dotnet build -c Release --no-restore
      - name: publish Windows version
        run: dotnet publish -c Release -o ./publish -r win-x86 -p:Version="${{env.VTAG}}" -p:PublishSingleFile=true --self-contained
      - name: rename Windows executable
        run: mv ./publish/PlexMatchGenerator.exe ./publish/PlexMatchGenerator-Windows-x86.exe
      - name: publish Linux version
        run: dotnet publish -c Release -o ./publish -r linux-x64 -p:Version="${{env.VTAG}}" -p:PublishSingleFile=true --self-contained
      - name: rename Linux executable
        run: mv ./publish/PlexMatchGenerator ./publish/PlexMatchGenerator-Linux-x64
      - name: publish Mac version
        run: dotnet publish -c Release -o ./publish -r osx-x64 -p:Version="${{env.VTAG}}" -p:PublishSingleFile=true --self-contained
      - name: rename Mac OSX executable
        run: mv ./publish/PlexMatchGenerator ./publish/PlexMatchGenerator-MacOSX-x64
      - name: remove debug artifacts
        run: rm ./publish/*.pdb -fr
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: ./publish